### ISSUE TITLE
syntax highlighting triggers on apostrophe

### ISSUE THREAD

**Issue by nmz787** [jvantuyl/sublime_diagram_plugin#69]
if I have a lines like this:
```
:don't break the code!|
:you're coding all night|
```
the text between the apostrophe's is assumed to be a quote. In this example the highlighting stops on the second line, but in my specific case I only had one apostrophe and no more after for 10 lines or more... so the entire remainder of the document is highlighted yellow as a result.

**Comment by nmz787** [comment]
I think this might fix it:
```
- match: (?:^[^:])\'
      scope: string.quoted.single.source.wsd
      push:
        - meta_scope: string.quoted.single.source.wsd
        - match: \'
          pop: true
```
